name: Auto Post Karakeep feed

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

# Grant write access to repository contents
permissions:
  contents: write

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install playwright feedparser
          playwright install chromium --with-deps

      - name: Run Script for News
        env:
          X_COOKIES: ${{ secrets.X_COOKIES }}
        run: python tweet_browser.py "https://keep.grange85.co.uk/api/v1/rss/lists/fok868roy772b9vn11t9hran?token=12768d7138cca9450bb9e9928c88ae2c364fa6089556a745a07f8a5126a2b21c"

      # Automatically commit history changes back to Github
      - name: Commit and Push History Log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add tweeted_history.txt || true
          git commit -m "Update tweeted history log [skip ci]" || true
          git push

